apiVersion: v1
kind: Pod
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  containers:
  - name: config-server
    image: {{DMALL_DOCKER_REGISTRY}}/dmall/config-server:latest
    ports:
    - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    nodePort: 30088
  selector:
    app: config-server